# Generated by Django 4.2.3 on 2024-02-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0003_repas_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse',
            field=models.TextField(default='Votre adresse par défaut'),
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse_email',
            field=models.EmailField(default='email@par_defaut.com', max_length=254),
        ),
        migrations.AddField(
            model_name='commande',
            name='menu_commande',
            field=models.CharField(default='Menu par défaut', max_length=255),
        ),
        migrations.AddField(
            model_name='commande',
            name='nom',
            field=models.CharField(default='Valeur par défaut', max_length=255),
        ),
        migrations.AddField(
            model_name='commande',
            name='nombre_de_plats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commande',
            name='numero_telephone',
            field=models.CharField(default='0 0 0 0 0', max_length=15),
        ),
    ]
