# Generated by Django 4.2.3 on 2024-02-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0004_commande_adresse_commande_adresse_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='adresse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='adresse_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='commande',
            name='menu_commande',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commande',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commande',
            name='nombre_de_plats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='numero_telephone',
            field=models.CharField(max_length=15),
        ),
    ]
