# Generated by Django 4.2.3 on 2024-02-13 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0005_alter_commande_adresse_alter_commande_adresse_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='repas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restau.repas'),
            preserve_default=False,
        ),
    ]
