# Generated by Django 4.2.3 on 2024-02-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0006_commande_repas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='repas',
        ),
    ]
